### ISSUE TITLE
2.4 regression - not catching calls through imgsrv.roll20.net

### ISSUE THREAD

**Issue by KenGitsIt** [flamewave000/plutonium-mirror#2]
Version 2.4 is back to the previous behavior of not catching the calls that go through imgsrv.roll20.net.  I reverted to 2.3, and it worked correctly again.

**Comment by flamewave000** [comment]
Apologies, I can see where the regression occurred. I'll get a fix out for this.

**Comment by flamewave000** [comment]
Released into v2.4.1

**Comment by KenGitsIt** [comment]
Confirmed that the fix did the trick!
